services:
  postgres:
    #    name of image on docker
    image: postgres:15
    #    mame of container
    container_name: paint
    #?????
    restart: always
    environment:
      #      user name
      POSTGRES_USER: paint
      POSTGRES_PASSWORD: 12
      POSTGRES_DB: paint
    #      any port of that
    ports:
      - "5432:5432"
    #      ????
    volumes:
      - pgdata:/var/lib/postgresql/data
#????????
volumes:
  pgdata:
